version: '3'

services:
  # Movies API
  movies-api:
    container_name: movies-api
    build: ./
    command: npm run dev
    working_dir: /usr/src/movies-api
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: movies_db
      REDIS_URL: 'redis://redis_server:6379/0'
    ports:
      - "3000:3000"
    depends_on: 
      - db
      - redis_server
    volumes:
      - ./:/usr/src/movies-api
  
  # Database Service
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    ports:
      - "3306:3306"
  
  # redis service
  redis_server:
    image: redis
    environment: 
      REDIS_URL: redis://127.0.0.1:6379/0